server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.lings.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring的配置
spring:
  application:
    name: Spring-Cloud-ProviderDept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=GMT%2B8&useUnicode=true&charaterEncoding=UTF-8
    username: root
    password:

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: Spring-Cloud-ProviderDept-8001  # 修改Eureka上面的默认描述信息
    prefer-ip-address: true #变成ip显示

#info配置
info:
  app.name: Lings
  company.name: Cai